databases:
  - name: django-blog-db
    databaseName: django_blog_db
    user: django_blog_user
    plan: free

services:
  - type: web
    name: django-blog
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myblog.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-blog-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "myblog.settings"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False"