# Generated by Django 5.2.4 on 2025-07-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique_for_date='publish', verbose_name='スラッグ'),
        ),
    ]
