# Generated by Django 5.2.4 on 2025-07-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive', models.CharField(help_text='script-src, style-src など', max_length=100, verbose_name='違反ディレクティブ')),
                ('blocked_uri', models.TextField(blank=True, help_text='違反したリソースのURI', verbose_name='ブロックされたURI')),
                ('document_uri', models.TextField(help_text='違反が発生したページのURI', verbose_name='ドキュメントURI')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='行番号')),
                ('column_number', models.IntegerField(blank=True, null=True, verbose_name='列番号')),
                ('source_file', models.TextField(blank=True, verbose_name='ソースファイル')),
                ('original_policy', models.TextField(help_text='違反したCSPポリシー', verbose_name='元のポリシー')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='発生日時')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='対応済み')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': 'CSP違反レポート',
                'verbose_name_plural': 'CSP違反レポート',
                'ordering': ('-created',),
            },
        ),
    ]
