# Generated by Django 5.2.4 on 2025-09-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
